//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="VentasSoap", Namespace="http://tempuri.org/")]
public partial class Ventas : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback nuevaVentaOperationCompleted;
    
    private System.Threading.SendOrPostCallback getVentasOperationCompleted;
    
    private System.Threading.SendOrPostCallback getVentasActivasOperationCompleted;
    
    private System.Threading.SendOrPostCallback getVentasEsperaOperationCompleted;
    
    private System.Threading.SendOrPostCallback getPujasVentaOperationCompleted;
    
    private System.Threading.SendOrPostCallback editarVentaOperationCompleted;
    
    private System.Threading.SendOrPostCallback finalizarVentaOperationCompleted;
    
    /// <remarks/>
    public Ventas() {
        this.Url = "http://192.168.1.16:6543/Ventas.asmx";
    }
    
    /// <remarks/>
    public event nuevaVentaCompletedEventHandler nuevaVentaCompleted;
    
    /// <remarks/>
    public event getVentasCompletedEventHandler getVentasCompleted;
    
    /// <remarks/>
    public event getVentasActivasCompletedEventHandler getVentasActivasCompleted;
    
    /// <remarks/>
    public event getVentasEsperaCompletedEventHandler getVentasEsperaCompleted;
    
    /// <remarks/>
    public event getPujasVentaCompletedEventHandler getPujasVentaCompleted;
    
    /// <remarks/>
    public event editarVentaCompletedEventHandler editarVentaCompleted;
    
    /// <remarks/>
    public event finalizarVentaCompletedEventHandler finalizarVentaCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nuevaVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void nuevaVenta(string ventaJson) {
        this.Invoke("nuevaVenta", new object[] {
                    ventaJson});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginnuevaVenta(string ventaJson, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("nuevaVenta", new object[] {
                    ventaJson}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndnuevaVenta(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void nuevaVentaAsync(string ventaJson) {
        this.nuevaVentaAsync(ventaJson, null);
    }
    
    /// <remarks/>
    public void nuevaVentaAsync(string ventaJson, object userState) {
        if ((this.nuevaVentaOperationCompleted == null)) {
            this.nuevaVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevaVentaOperationCompleted);
        }
        this.InvokeAsync("nuevaVenta", new object[] {
                    ventaJson}, this.nuevaVentaOperationCompleted, userState);
    }
    
    private void OnnuevaVentaOperationCompleted(object arg) {
        if ((this.nuevaVentaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.nuevaVentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string getVentas(int idUsuario) {
        object[] results = this.Invoke("getVentas", new object[] {
                    idUsuario});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetVentas(int idUsuario, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getVentas", new object[] {
                    idUsuario}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetVentas(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getVentasAsync(int idUsuario) {
        this.getVentasAsync(idUsuario, null);
    }
    
    /// <remarks/>
    public void getVentasAsync(int idUsuario, object userState) {
        if ((this.getVentasOperationCompleted == null)) {
            this.getVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVentasOperationCompleted);
        }
        this.InvokeAsync("getVentas", new object[] {
                    idUsuario}, this.getVentasOperationCompleted, userState);
    }
    
    private void OngetVentasOperationCompleted(object arg) {
        if ((this.getVentasCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getVentasCompleted(this, new getVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVentasActivas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string getVentasActivas(int userId) {
        object[] results = this.Invoke("getVentasActivas", new object[] {
                    userId});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetVentasActivas(int userId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getVentasActivas", new object[] {
                    userId}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetVentasActivas(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getVentasActivasAsync(int userId) {
        this.getVentasActivasAsync(userId, null);
    }
    
    /// <remarks/>
    public void getVentasActivasAsync(int userId, object userState) {
        if ((this.getVentasActivasOperationCompleted == null)) {
            this.getVentasActivasOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVentasActivasOperationCompleted);
        }
        this.InvokeAsync("getVentasActivas", new object[] {
                    userId}, this.getVentasActivasOperationCompleted, userState);
    }
    
    private void OngetVentasActivasOperationCompleted(object arg) {
        if ((this.getVentasActivasCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getVentasActivasCompleted(this, new getVentasActivasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVentasEspera", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string getVentasEspera(int userId) {
        object[] results = this.Invoke("getVentasEspera", new object[] {
                    userId});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetVentasEspera(int userId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getVentasEspera", new object[] {
                    userId}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetVentasEspera(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getVentasEsperaAsync(int userId) {
        this.getVentasEsperaAsync(userId, null);
    }
    
    /// <remarks/>
    public void getVentasEsperaAsync(int userId, object userState) {
        if ((this.getVentasEsperaOperationCompleted == null)) {
            this.getVentasEsperaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVentasEsperaOperationCompleted);
        }
        this.InvokeAsync("getVentasEspera", new object[] {
                    userId}, this.getVentasEsperaOperationCompleted, userState);
    }
    
    private void OngetVentasEsperaOperationCompleted(object arg) {
        if ((this.getVentasEsperaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getVentasEsperaCompleted(this, new getVentasEsperaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPujasVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string getPujasVenta(int idVenta) {
        object[] results = this.Invoke("getPujasVenta", new object[] {
                    idVenta});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetPujasVenta(int idVenta, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getPujasVenta", new object[] {
                    idVenta}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetPujasVenta(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getPujasVentaAsync(int idVenta) {
        this.getPujasVentaAsync(idVenta, null);
    }
    
    /// <remarks/>
    public void getPujasVentaAsync(int idVenta, object userState) {
        if ((this.getPujasVentaOperationCompleted == null)) {
            this.getPujasVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPujasVentaOperationCompleted);
        }
        this.InvokeAsync("getPujasVenta", new object[] {
                    idVenta}, this.getPujasVentaOperationCompleted, userState);
    }
    
    private void OngetPujasVentaOperationCompleted(object arg) {
        if ((this.getPujasVentaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getPujasVentaCompleted(this, new getPujasVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void editarVenta(int id, System.DateTime newDate) {
        this.Invoke("editarVenta", new object[] {
                    id,
                    newDate});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegineditarVenta(int id, System.DateTime newDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("editarVenta", new object[] {
                    id,
                    newDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndeditarVenta(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void editarVentaAsync(int id, System.DateTime newDate) {
        this.editarVentaAsync(id, newDate, null);
    }
    
    /// <remarks/>
    public void editarVentaAsync(int id, System.DateTime newDate, object userState) {
        if ((this.editarVentaOperationCompleted == null)) {
            this.editarVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarVentaOperationCompleted);
        }
        this.InvokeAsync("editarVenta", new object[] {
                    id,
                    newDate}, this.editarVentaOperationCompleted, userState);
    }
    
    private void OneditarVentaOperationCompleted(object arg) {
        if ((this.editarVentaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.editarVentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/finalizarVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void finalizarVenta(int ventaId, int motiv, int idComprador) {
        this.Invoke("finalizarVenta", new object[] {
                    ventaId,
                    motiv,
                    idComprador});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfinalizarVenta(int ventaId, int motiv, int idComprador, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("finalizarVenta", new object[] {
                    ventaId,
                    motiv,
                    idComprador}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndfinalizarVenta(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void finalizarVentaAsync(int ventaId, int motiv, int idComprador) {
        this.finalizarVentaAsync(ventaId, motiv, idComprador, null);
    }
    
    /// <remarks/>
    public void finalizarVentaAsync(int ventaId, int motiv, int idComprador, object userState) {
        if ((this.finalizarVentaOperationCompleted == null)) {
            this.finalizarVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfinalizarVentaOperationCompleted);
        }
        this.InvokeAsync("finalizarVenta", new object[] {
                    ventaId,
                    motiv,
                    idComprador}, this.finalizarVentaOperationCompleted, userState);
    }
    
    private void OnfinalizarVentaOperationCompleted(object arg) {
        if ((this.finalizarVentaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.finalizarVentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void nuevaVentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void getVentasCompletedEventHandler(object sender, getVentasCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void getVentasActivasCompletedEventHandler(object sender, getVentasActivasCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getVentasActivasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getVentasActivasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void getVentasEsperaCompletedEventHandler(object sender, getVentasEsperaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getVentasEsperaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getVentasEsperaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void getPujasVentaCompletedEventHandler(object sender, getPujasVentaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getPujasVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getPujasVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void editarVentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void finalizarVentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
